# Generated by Django 2.1.5 on 2024-03-29 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0008_auto_20240325_2210'),
        ('rango', '0002_auto_20240329_2144'),
    ]

    operations = [
    ]
